### ISSUE TITLE
NoClassDefFoundError: org/deeplearning4j/nn/conf/layers/Layer

### ISSUE THREAD

**Issue by vallettea** [deeplearning4j/dl4j-spark-ml-examples#11]
hello,

i'm trying to run  inside the prediction.io framework. my code compiles but i get a runtime error that i can't figure out:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/deeplearning4j/nn/conf/layers/Layer
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2595)
	at java.lang.Class.getConstructors(Class.java:1530)
	at io.prediction.workflow.WorkflowUtils$.extractParams(WorkflowUtils.scala:136)
	at io.prediction.controller.Engine$$anonfun$10$$anonfun$apply$6.apply(Engine.scala:346)
	at io.prediction.controller.Engine$$anonfun$10$$anonfun$apply$6.apply(Engine.scala:342)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at io.prediction.controller.Engine$$anonfun$10.apply(Engine.scala:342)
	at io.prediction.controller.Engine$$anonfun$10.apply(Engine.scala:339)
	at scala.Option.map(Option.scala:145)
	at io.prediction.controller.Engine.jValueToEngineParams(Engine.scala:339)
	at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:228)
	at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

my build.sbt:

```
import AssemblyKeys._

assemblySettings

name := "test"

organization := "io.prediction"

libraryDependencies ++= Seq(
  "io.prediction"    %% "core"          % pioVersion.value % "provided",
  "org.apache.spark" %% "spark-core"    % "1.4.0" % "provided",
  "org.apache.spark" %% "spark-mllib"   % "1.4.0" % "provided",
  "org.nd4j" % "nd4j-x86" % "0.4-rc0" % "provided",
  "org.nd4j" % "nd4j-api" % "0.4-rc0" % "provided",
  "org.deeplearning4j" % "dl4j-spark-ml" % "0.4-rc0" % "provided"
)


mergeStrategy in assembly <<= (mergeStrategy in assembly) { mergeStrategy => {
 case entry => {
   val strategy = mergeStrategy(entry)
   if (strategy == MergeStrategy.deduplicate) MergeStrategy.last
   else strategy
 }
}}
```

it might be specific to prediction.io but i you have a clue, i'd be glad...

**Comment by agibsonccc** [comment]
So: "org.nd4j" % "nd4j-x86" % "0.4-rc0" % "provided",
  "org.nd4j" % "nd4j-api" % "0.4-rc0" % "provided",
  "org.deeplearning4j" % "dl4j-spark-ml" % "0.4-rc0" % "provided"

(I"m not an sbt expert prefacing this now)

When you use provided scope here it auto excludes all the deps. Shouldn't you use these as included with leaving spark excluded? Spark excluded means provided at runtime (which is the case with spark)

**Comment by EronWright** [comment]
Adam's understanding is correct that 'provided' indicates that the hosting environment will provide the dependency.    Usually Spark is marked as provided for obvious reasons.     @vallettea is nonetheless correct to mark dl4j as provided too, _if you're the dl4j Spark Package_ as the examples do.    

It is subtle and I will improve the instructions.   Look at [bin/run-example](https://github.com/deeplearning4j/dl4j-spark-ml-examples/blob/master/bin/run-example) to see that the spark-package is given to `spark-submit`, _in addition to_ the application jar.   The application jar need not be an uber-jar thanks to this new approach.

```
exec spark-submit \
  --packages "deeplearning4j:dl4j-spark-ml:0.4-rc0" \
  --master $EXAMPLE_MASTER \
  --class $EXAMPLE_CLASS \
  --driver-memory 1G \
  --executor-memory 4G \
  "$SPARK_EXAMPLES_JAR" \
```

**Comment by agibsonccc** [comment]
Should this be marked as a doc issue and closed post instructions update?

**Comment by vallettea** [comment]
thanks for your help, I solved my problem by using spark 1.4.1 (I was using 1.2) and with the following configuration:
```
libraryDependencies ++= Seq(
  "io.prediction"    %% "core"          % pioVersion.value % "provided",
  "org.apache.spark" %% "spark-core"    % "1.4.1" % "provided",
  "org.apache.spark" %% "spark-mllib"   % "1.4.1" % "provided",
  "org.nd4j" % "nd4j-x86" % "0.4-rc0",
  "org.nd4j" % "nd4j-api" % "0.4-rc0",
  "org.deeplearning4j" % "dl4j-spark-ml" % "0.4-rc0"
)
```

**Comment by EronWright** [comment]
Leaving it open for a doc update.
